name: biomae
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - tqdm
  - pillow
  - pyyaml
  - jupyter
  - ipywidgets
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  - pip:
      - ultralytics
      - opencv-python
      - seaborn
